apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: acme-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: acme-http
    hostname: "*.dremer10.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
